server:
  port: 9000
spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: password
  liquibase:
    change-log: classpath:/migrations.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  main:
    web-application-type: servlet
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html